
--CSV to Flink table queries

SELECT
  SPLIT_INDEX(CAST(val AS STRING), '|', 0)  AS CI_ID,
  SPLIT_INDEX(CAST(val AS STRING), '|', 1)  AS UPDT_SEQ_N,
  SPLIT_INDEX(CAST(val AS STRING), '|', 2)  AS CI_SSN_ID,
  SPLIT_INDEX(CAST(val AS STRING), '|', 3)  AS CI_BIR_DT,
  SPLIT_INDEX(CAST(val AS STRING), '|', 4)  AS CI_FRST_NM,
  SPLIT_INDEX(CAST(val AS STRING), '|', 5)  AS CI_MID_NM,
  SPLIT_INDEX(CAST(val AS STRING), '|', 6)  AS CI_LAST_NM,
  SPLIT_INDEX(CAST(val AS STRING), '|', 7)  AS CI_PFX_NM,
  SPLIT_INDEX(CAST(val AS STRING), '|', 8)  AS CI_SFX_NM,
  SPLIT_INDEX(CAST(val AS STRING), '|', 9)  AS CI_SEX_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 10) AS EMP_STUS_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 11) AS CI_COMM_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 12) AS CI_ADR_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 13) AS CI_MAR_STUS_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 14) AS CI_REL_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 15) AS CI_CARD_NM_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 16) AS CI_EFF_DT,
  SPLIT_INDEX(CAST(val AS STRING), '|', 17) AS CI_CAN_DT,
  SPLIT_INDEX(CAST(val AS STRING), '|', 18) AS CI_CAN_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 19) AS SYS_STUS_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 20) AS NM_ORD_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 21) AS EMP_CLSS_C_1,
  SPLIT_INDEX(CAST(val AS STRING), '|', 22) AS EMP_CLSS_C_2,
  SPLIT_INDEX(CAST(val AS STRING), '|', 23) AS EMP_CLSS_C_3,
  SPLIT_INDEX(CAST(val AS STRING), '|', 24) AS MLT_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 25) AS CI_ID_SEQ_N,
  SPLIT_INDEX(CAST(val AS STRING), '|', 26) AS LAST_MTN_DT,
  SPLIT_INDEX(CAST(val AS STRING), '|', 27) AS LAST_MTN_TM,
  SPLIT_INDEX(CAST(val AS STRING), '|', 28) AS LAST_MTN_ID,
  SPLIT_INDEX(CAST(val AS STRING), '|', 29) AS CLI_ID,
  SPLIT_INDEX(CAST(val AS STRING), '|', 30) AS CH_AGR_ID,
  SPLIT_INDEX(CAST(val AS STRING), '|', 31) AS CI_POS_SEQ_N,
  SPLIT_INDEX(CAST(val AS STRING), '|', 32) AS CI_CAPN_UNQ_MBR_ID,
  SPLIT_INDEX(CAST(val AS STRING), '|', 33) AS CI_HRE_DT,
  SPLIT_INDEX(CAST(val AS STRING), '|', 34) AS CI_APLN_RCT_DT,
  SPLIT_INDEX(CAST(val AS STRING), '|', 35) AS CI_APLN_SIG_DT,
  SPLIT_INDEX(CAST(val AS STRING), '|', 36) AS NSMIR_CD,
  SPLIT_INDEX(CAST(val AS STRING), '|', 37) AS BPD_ID,
  SPLIT_INDEX(CAST(val AS STRING), '|', 38) AS CNSM_ID
FROM HST_CI;


SELECT
  SPLIT_INDEX(CAST(val AS STRING), '|', 0)  AS CI_ID,
  SPLIT_INDEX(CAST(val AS STRING), '|', 1)  AS CI_ADR_QLFR_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 2)  AS UPDT_SEQ_N,
  SPLIT_INDEX(CAST(val AS STRING), '|', 3)  AS CI_AL_1,
  SPLIT_INDEX(CAST(val AS STRING), '|', 4)  AS CI_AL_2,
  SPLIT_INDEX(CAST(val AS STRING), '|', 5)  AS CI_AL_3,
  SPLIT_INDEX(CAST(val AS STRING), '|', 6)  AS CI_AL_4,
  SPLIT_INDEX(CAST(val AS STRING), '|', 7)  AS CI_CY,
  SPLIT_INDEX(CAST(val AS STRING), '|', 8)  AS CI_ST,
  SPLIT_INDEX(CAST(val AS STRING), '|', 9)  AS CI_Z_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 10) AS CI_CNTRY_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 11) AS CI_ADR_EFF_DT,
  SPLIT_INDEX(CAST(val AS STRING), '|', 12) AS CI_ADR_CAN_DT,
  SPLIT_INDEX(CAST(val AS STRING), '|', 13) AS SYS_STUS_C,
  SPLIT_INDEX(CAST(val AS STRING), '|', 14) AS LAST_MTN_DT,
  SPLIT_INDEX(CAST(val AS STRING), '|', 15) AS LAST_MTN_TM,
  SPLIT_INDEX(CAST(val AS STRING), '|', 16) AS LAST_MTN_ID,
  SPLIT_INDEX(CAST(val AS STRING), '|', 17) AS CI_CNTY_C
FROM HST_CI_ADR;






